---
# this is identical to config.yml, except s/module/win_module/

- name: (win) Write agent.tags.conf
  win_template:
    src: agent.tags.conf.j2
    dest: "{{ te_agent_package_install_path }}/data/config/agent.tags.conf"
  when: te_agent_tags is defined

- name: (win) webserver.http.port
  win_lineinfile:
    path: "{{ te_agent_package_install_path }}/data/config/agent.properties"
    regexp: '^webserver\.http\.port='
    line: 'webserver.http.port={{ te_agent_te_server_http_port }}'
  notify:
    - Restart Windows agent service

- name: (win) tw.server.host
  win_lineinfile:
    path: "{{ te_agent_package_install_path }}/data/config/agent.properties"
    regexp: '^tw\.server\.host='
    line: 'tw.server.host={{ te_agent_te_server_host }}'
  notify:
    - Restart Windows agent service

- name: (win) tw.server.port
  win_lineinfile:
    path: "{{ te_agent_package_install_path }}/data/config/agent.properties"
    regexp: '^tw\.server\.port='
    line: 'tw.server.port={{ te_agent_te_services_port }}'
  notify:
    - Restart Windows agent service

- name: (win) tw.agent.generator.port
  win_lineinfile:
    path: "{{ te_agent_package_install_path }}/data/config/agent.properties"
    regexp: '^tw\.agent\.generator\.port='
    line: 'tw.agent.generator.port={{ te_agent_rtm_port }}'
  notify:
    - Restart Windows agent service
    - Restart Windows event generator service

- name: (win) tw.local.port
  win_lineinfile:
    path: "{{ te_agent_package_install_path }}/data/config/agent.properties"
    regexp: '^tw\.local\.port='
    line: 'tw.local.port={{ te_agent_local_port }}'
  notify:
    - Restart Windows agent service

- name: (win) tw.proxy.host
  win_lineinfile:
    path: "{{ te_agent_package_install_path }}/data/config/agent.properties"
    regexp: '^tw\.proxy\.host='
    line: 'tw.proxy.host={{ te_agent_proxy_host }}'
  when: te_agent_proxy_host is defined
  notify:
    - Restart Windows agent service

- name: (win) tw.proxy.port
  win_lineinfile:
    path: "{{ te_agent_package_install_path }}/data/config/agent.properties"
    regexp: '^tw\.proxy\.port='
    line: 'tw.proxy.port={{ te_agent_proxy_port }}'
  when: te_agent_proxy_host is defined
  notify:
    - Restart Windows agent service
